### ISSUE TITLE
Unable to build with --prod 

### ISSUE THREAD

**Issue by tom94zoe** [anjmao/ng-validators#1]
If I try to build/serve my application with  the --prod flag, unfortunately the following error message occures. 

ERROR in : Unexpected value 'undefined' exported by the module 'CustomFormsModule in C:/Users/.../Documents/...../node_modules/@ng-validators/ng-validators/ng-validators.d.ts'

Angular Version: 5.2.4
ng-valdiators: 0.10.1

Are there any known solutions for this problem?

**Comment by tom94zoe** [comment]
updated to ng-validators: 0.10.4

removed CustomFormModule and added used directive to my module [delcrations and exports].

Normal serve works, but with the flag --prod I got following error message: 

ERROR in : Unexpected value 'EqualValidator in C:/Users/.../Documents/.../node_modules/@ng-validators/ng-validators/equal/directive.d.ts' declared by the module 'CustomComponentsModule in C:/Users
/.../Documents/.../src/app/shared/custom-components/custom-components.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by anjmao** [comment]
Hi @tom94zoe, I'm looking into this issue, hope to fix it today, thanks for reporting.

**Comment by tom94zoe** [comment]
Thank you ;)

**Comment by anjmao** [comment]
There is an issue with angular itself, it does not allow to create library without NgModule. Here is bug which I registered https://github.com/angular/angular/issues/23475.

**Comment by anjmao** [comment]
I pushed updated version with exposed NgValidatorsModule.

**Comment by tom94zoe** [comment]
Thank you. I‘ll try it later, today
